name: Activate Unity
on:
  push:
    branches:
      - never
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: 2020.1.3f1
      # - name: Copy
      #   run: |
      #     echo PATH=${{ steps.getManualLicenseFile.outputs.filePath }}
      #     cat ${{ steps.getManualLicenseFile.outputs.filePath }}
      #     zip my-license ${{ steps.getManualLicenseFile.outputs.filePath }}
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}