name: Nightly Build

on:
  schedule:
    - cron: '0 1 * * *'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build_nightly:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.3f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: webbertakken/unity-builder@v1.2
        with:
          customParameters: -nographics
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
  slack_notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: build_nightly
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - uses: Ilshidur/action-slack@2.0.2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          args: Build failed for https://github.com/${{ github.repository }}
